zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000
      sensitive-headers:
    user:
      path: /user/**
      url: http://localhost:9898/uaa/user

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:9898/uaa/oauth/token
      userAuthorizationUri: http://localhost:9898/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: http://localhost:9898/uaa/user