spring:
  application:
    name: sampleapp # Give a name for the app. THis will be used for the service name in consul registration.
  cloud:
    consul:
      discovery:
        enabled: true # Enable/ disable the service(app) registration to consul.
        fail-fast: false # If consul is not reachable, the app doesn't crash
        tags: springapp, sampleapp, foo, bar # Tags for our service
        # Making the Consul Instance ID Unique
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        health-check-interval: 15s # How often should consul access the health check endpoint "/health"

